# Generated by Django 4.2 on 2023-04-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectitem',
            name='skills_list',
        ),
        migrations.AddField(
            model_name='projectitem',
            name='skills_json_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
