# Generated by Django 4.2 on 2023-04-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_projectitem_skills_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectitem',
            name='skills_json_list',
        ),
        migrations.AddField(
            model_name='projectitem',
            name='skills',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
