# Generated by Django 4.2 on 2023-04-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_projectitem_skills_json_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
